# Generated by Django 6.1.1 on 2026-09-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('vehicle_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('plate_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('plate_crop_path', models.CharField(blank=True, max_length=500)),
                ('bounding_box', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detections', to='cameras.camera')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detections', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['vehicle', 'detected_at'], name='detection_vehicle_time_idx'), models.Index(fields=['camera', 'detected_at'], name='detection_camera_time_idx')],
            },
        ),
    ]
